### ISSUE TITLE
 didn't processing with comment

### ISSUE THREAD

**Issue by Jeongyong-park** [paulschwarz/spring-dotenv#28]
I needed a comment among the settings in the .env file, so I wrote down the value by adding a hashtag to the right of the value.

Looking at the error log, the value injected with spring-dotenv includes a hashtag annotation marked as a comment.

**my .env file**

``` env
DB_HOSTNAME = 192.168.10.172 #localhost
DB_PORT = 15432
```

```yml
spring:
    application:
        name: pdp22backend
    profiles:
        active: native, default;
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${APP_DB_NAME}
...
```

**error log**

``` sh
Caused by: java.net.UnknownHostException: 192.168.10.172 #localhost
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
```
